# RunTest.srv
string[] dofs        # e.g. ["X_DOF", "Y_DOF", "N_DOF"]
float32[] forces     # e.g. [0.5, -0.2, 0.1]
float32 duration
float32 publish_rate
float32 startup_delay
---
bool success
string message